all:
	# install mysnippet
	@cd $$HOME/.vim && ls mysnippets > /dev/null || git clone git@github.com:grepinsight/mysnippets.git
	@cd $$HOME/.vim && ls ftplugin   > /dev/null || git clone git@github.com:grepinsight/ftplugin.git
