all:
	@cd $$HOME/.vim && ls mysnippets > /dev/null || ln -sf $$HOME/.config/nvim/mysnippets $$HOME/.vim/mysnippets
	@cd $$HOME/.vim && ls ftplugin   > /dev/null || ln -sf $$HOME/.config/nvim/ftplugin $$HOME/.vim/ftplugin
	mkdir -p spell
