all:
	mkdir -p $$HOME/.config/rstudio/
	ln -sf $$HOME/.dotfiles/rstudio/rstudio-prefs.json $$HOME/.config/rstudio/rstudio-prefs.json
	bash scripts/link-rstudio-snippets-and-bindings.sh # link rstudio scripts
