snippet wdl "Description" b
FROM python:3.6

RUN apt-get update && apt-get install -y python-dev
RUN pip install --upgrade pip

# avoid cache invalidation on change to files within ./src
COPY ./requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt

COPY ./shrink_data_frame /code
WORKDIR /code

endsnippet
